### Get all trips
GET localhost:8000/companion/api/trips/?id=d13ebf7d-4512-42a9-99bc-cca0f850bed0

### Create a trip
POST localhost:8000/companion/api/trips/
Content-Type: application/json

{
    "profile": "martin",
    "start": "Karlsruhe",
    "destination": "Munchen",
    "vehicle_type": "TRAIN_LONG",
    "co2_emissions": 42.01
}

### Update a trip
PUT localhost:8000/companion/api/trips/
Content-Type: application/json

{
  "id": "88ca6f84-acd4-4b5d-aa8b-ab779fe51434",
  "destination": "Berlin",
  "vehicle_type": "TRAIN_SHORT"
}

### Delete a trip
DELETE localhost:8000/companion/api/trips/
Content-Type: application/json

{
    "id": "88ca6f84-acd4-4b5d-aa8b-ab779fe51434"
}

