# Generated by Django 5.0.3 on 2024-03-26 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=255)),
                ('start', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('CAR_DIESEL', 'Car Diesel'), ('CAR_PETROL', 'Car Petrol'), ('CAR_ELECTRIC', 'Car Electric'), ('WALKING', 'WALKING'), ('BIKE', 'Cycling'), ('MIXED', 'MIXED'), ('TRAIN_SHORT', 'Train regional'), ('TRAIN_LONG', 'Train international')], default='TRAIN_SHORT', max_length=50)),
                ('co2_emissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('username', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companion.profile')),
            ],
        ),
    ]
